module XpRules
  PROFILE_CREATED = 100
  ACHIEVEMENT_UNLOCKED = 5
  CHAIN_CREATED = 50
  CHAIN_DESCRIPTION_BONUS = 25
  ACHIEVEMENT_ADDED_TO_CHAIN = 5
  ACHIEVEMENT_NOTE_BONUS = 3
  CHAIN_COMPLETED = 100
end
