:scheduler:
  :schedule:
    enqueue_user_achievement_syncs:
      cron: "5 * * * *"
      class: EnqueueUserAchievementSyncsWorker
    sync_user_profiles:
      cron: "0 4 * * *"
      class: SyncUserProfilesWorker
